### ISSUE TITLE
Adding custom thirdparty scripts, e.g. <script src=".."

### ISSUE THREAD

**Issue by knownasilya** [gdub22/ember-cli-inline-content#10]
Moved from #3 

Would love being able to add scripts with a src, where the script isn't processed, without having to write HTML markup, with the ability to add query params.

```js
inlineContent: {
  'gmaps-api': {
    url: '//maps.googleapis.com/maps/api/js',
    params: {
      v: '3.exp',
      libraries: ['drawing', 'geometry'].join(',')
    }
  }
}
```

Then you can change the version to stable in production, and add a clientId or an apikey.

Also supporting `'gmaps-api': '[http:|https:|etc]//maps.googleapis.com/maps/api/js'` where a check is performed if it's a path or a url, if url set as `src`, otherwise put inside.

**Comment by gdub22** [comment]
@knownasilya if we go with `url`, that should be explicit enough to know to set it as `src`, where the `file` option is already in place that knows to inline the content.

One issue here is determining if it needs a `script` or `link` tag, which is not distinguishable by your example url.

**Comment by knownasilya** [comment]
Maybe default to script, but also having a `type: 'script'` if it's not distinguishable.

**Comment by gdub22** [comment]
@knownasilya that sounds good. PRs welcomed or I'll get to it in the next week or so.

**Comment by rwwagner90** [comment]
@gdub22 did you ever get to this?

**Comment by gdub22** [comment]
No I did not. Looking back at it, this feels like an over-abstraction.  You can just use the string injection technique to achieve this.

https://github.com/gdub22/ember-cli-inline-content#rendering-a-string-of-content-instead-of-a-file
