### ISSUE TITLE
Add ability to vary inline content depends of route.

### ISSUE THREAD

**Issue by ofry** [gdub22/ember-cli-inline-content#13]
For example, I have router.js:

```
import Ember from 'ember';
import config from './config/environment';

const Router = Ember.Router.extend({
  location: config.locationType
});

Router.map(function() {
  this.route('user', function() {
    this.route('register');
    this.route('login');
  });
});

export default Router;
```

Then I want custom <body> attributes.

I did in app/index.html like that:

<body class="hold-transition {{content-for 'body_styles'}}">

In ember-cli-build.js I did something like:

```
inlineContent: {
      'body_styles': {
        content: "skin-blue sidebar-mini"
      }
    }
```

But I want to vary body_styles replacement string depend of application route. For example, for route user/register I need:

```
      'body_styles': {
        content: "register_page"
      }
```

etc, etc. How can I do that? Thanks.

**Comment by gdub22** [comment]
This plugin is only for modifying index.html at build time.  If you want runtime modifications per route, that would go in your application code.
