### ISSUE TITLE
How to reference built assets?

### ISSUE THREAD

**Issue by rwwagner90** [gdub22/ember-cli-inline-content#14]
The assets now have paths like:

```html
  <link rel="stylesheet" href="{{rootURL}}assets/vendor.css">
  <link rel="stylesheet" href="{{rootURL}}assets/website.css">
```

How can I reference these with this addon to inline them?

**Comment by rwwagner90** [comment]
@gdub22 any advice?

**Comment by gdub22** [comment]
```js
inlineContent: {
  vendorCSS: '/dist/assets/vendor.css',
  websiteCSS: '/dist/assets/website.css'
}
```

**Comment by rwwagner90** [comment]
@gdub22 this doesn't seem to work. Isn't inlining the content part of generating the dist? Therefore, wouldn't there be no dist?

**Comment by gdub22** [comment]
It's working.  Make sure you place `{{content-for "vendorCSS"}}` placeholders, etc in your index.html.  See README.

**Comment by rwwagner90** [comment]
@gdub22 it does not work for me. It only works if you have previously run a build. The dist is not generated until you build. Blow away your dist and run a new build and you will see it does not work.

**Comment by gdub22** [comment]
Ah ok, not sure if possible then. PRs welcome if you figure it out.

**Comment by rwwagner90** [comment]
Don't think it is possible without running two builds or doing something to hijack the build

**Comment by rwwagner90** [comment]
I do not think this is possible without doing some custom build stuff and essentially running the build twice, so going to close.

**Comment by oskarrough** [comment]
Could this addon be configured to run after the `dist` is generated? Inlining the built, minified styled would be great.

**Comment by ianpetzer** [comment]
@oskarrough Did you have any success getting this working? I would love to be able to inline my minified app css straight into the index.html

**Comment by oskarrough** [comment]
@ianpetzer nah, couldn't figure it out. I ended up doing this https://gist.github.com/oskarrough/02833da29934ad34c1615ea2a15ff82e

**Comment by ianpetzer** [comment]
@oskarrough That looks really interesting. Thanks so much!
